# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: detect-aws-credentials
    - id: detect-private-key
    # - id: no-commit-to-branch

- repo: local
  hooks:
    - id: stylua
      name: StyLua
      entry: stylua
      language: system
      files: ^.*\.lua$


- repo: https://github.com/Woile/commitizen
  rev: v2.22.0
  hooks:
  - id: commitizen
    stages: [commit-msg]

ci:
  autofix_prs: false
  autoupdate_commit_msg: 'chore(pre-commit.ci): pre-commit autoupdate [skip ci]'
